name: Build Payload

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Android NDK
        run: |
          NDK_URL="https://dl.google.com/android/repository/android-ndk-r29-linux.zip"
          curl -SL --progress-bar "$NDK_URL" -o ndk.zip
          unzip -q ndk.zip -d $HOME/ndk
          rm ndk.zip
          
          NDK_HOME=$(find $HOME/ndk -maxdepth 2 -name "source.properties" | xargs dirname)
          echo "NDK_HOME=$NDK_HOME" >> $GITHUB_ENV
          echo "NDK_ROOT=$NDK_HOME" >> $GITHUB_ENV

      - name: Build payload.so
        run: |
          sed -i 's/\r$//' exploit/Makefile
          cd exploit
          make NDK="$NDK_HOME" \
               TOOLCHAIN="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64" \
               CC="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang" \
               SYSROOT="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot" \

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: payload-so-output
          path: exploit/preload.so
